Add support for app.sh script so have easy control over how application launched.

diff --git a/3.3/s2i/bin/run b/3.3/s2i/bin/run
--- a/3.3/s2i/bin/run
+++ b/3.3/s2i/bin/run
@@ -32,6 +32,18 @@ function get_default_web_concurrency() {
   echo $default
 }
 
+app_script_check="${APP_SCRIPT-}"
+APP_SCRIPT="${APP_SCRIPT:-app.sh}"
+if [[ -f "$APP_SCRIPT" ]]; then
+  echo "---> Running application from script ($APP_SCRIPT) ..."
+  if [[ "$APP_SCRIPT" != /* ]]; then
+    APP_SCRIPT="./$APP_SCRIPT"
+  fi
+  exec "$APP_SCRIPT"
+else
+  test -n "$app_script_check" && (>&2 echo "ERROR: file '$app_script_check' not found.") && exit 1
+fi
+
 app_file_check="${APP_FILE-}"
 APP_FILE="${APP_FILE:-app.py}"
 if [[ -f "$APP_FILE" ]]; then
