Fail with an error message when the APP_FILE variable is set incorrectly
Resolves: #86

diff --git a/3.5/s2i/bin/run b/3.5/s2i/bin/run
--- a/3.5/s2i/bin/run
+++ b/3.5/s2i/bin/run
@@ -32,12 +32,14 @@ function get_default_web_concurrency() {
   echo $default
 }
 
+app_file_check="${APP_FILE-}"
 APP_FILE="${APP_FILE:-app.py}"
 if [[ -f "$APP_FILE" ]]; then
   echo "---> Running application from Python script ($APP_FILE) ..."
   exec python "$APP_FILE"
+else
+  test -n "$app_file_check" && (>&2 echo "ERROR: file '$app_file_check' not found.") && exit 1
 fi
-echo "WARNING: file '$APP_FILE' not found."
 
 # Find shallowest manage.py script, either ./manage.py or <project>/manage.py
 manage_file=$(find . -maxdepth 2 -type f -name 'manage.py' -printf '%d\t%P\n' | sort -nk1 | cut -f2 | head -1)
