Support for Django applications

diff --git a/3.3/.sti/bin/assemble b/3.3/.sti/bin/assemble
--- a/3.3/.sti/bin/assemble
+++ b/3.3/.sti/bin/assemble
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+function is_django_installed() {
+  pip show -q django
+}
+
+function should_collectstatic() {
+  is_django_installed && [[ -z "$DISABLE_COLLECTSTATIC" ]]
+}
+
 set -e
 
 echo "---> Copying application source ..."
@@ -17,6 +25,30 @@ fi
 
 # set permissions for any installed artifacts
 chmod -R og+rwx /opt/openshift
+
+if should_collectstatic; then
+  (
+    echo "---> Collecting Django static files ..."
+
+    # Find shallowest manage.py script, either ./manage.py or <project>/manage.py
+    manage_file=$(find . -maxdepth 2 -type f -name 'manage.py' -printf '%d\t%P\n' | sort -nk1 | cut -f2 | head -1)
+
+    if [[ ! -f "$manage_file" ]]; then
+      echo "WARNING: seems that you're using Django, but we could not find a 'manage.py' file."
+      echo "'manage.py collectstatic' ignored."
+      exit
+    fi
+
+    if ! python $manage_file collectstatic --dry-run --noinput &> /dev/null; then
+      echo "WARNING: could not run 'manage.py collectstatic'. To debug, run:"
+      echo "    $ python $manage_file collectstatic --noinput"
+      echo "Ignore this warning if you're not serving static files with Django."
+      exit
+    fi
+
+    python $manage_file collectstatic --noinput
+  )
+fi
 
 # remove pip temporary directory
 rm -rf /tmp/pip_build_default
