Distgen generated content

diff --git a/3.6/s2i/bin/assemble b/3.6/s2i/bin/assemble
--- a/3.6/s2i/bin/assemble
+++ b/3.6/s2i/bin/assemble
@@ -57,6 +57,16 @@ mv /tmp/src/* "$HOME"
 # set permissions for any installed artifacts
 fix-permissions /opt/app-root -P
 
+# Python <3.7 only code, Python 3.7+ uses bundled wheel from Fedora
+# We have to first upgrade pip to at least 19.3 because:
+# * pip < 9 does not support different packages' versions for Python 2/3
+# * pip < 19.3 does not support manylinux2014 wheels. Only manylinux2014 (and later) wheels
+#   support platforms like ppc64le, aarch64 or armv7
+echo "---> Upgrading pip to latest version supported for Python $PYTHON_VERSION ..."
+if ! pip install -U "pip"; then
+  echo "WARNING: Installation of 'pip' failed, trying again from official PyPI with pip --isolated install"
+  pip install --isolated -U "pip"
+fi
 
 if [[ ! -z "$UPGRADE_PIP_TO_LATEST" ]]; then
   echo "---> Upgrading pip, setuptools and wheel to latest version ..."
