Install tools like pipenv or micropipenv from a mirror first
If you have a mirror with Python packages with dependencies
of your application, the s2i-python-container will try to install
internal tools like pipenv from that mirror as well. If that try
fails, the second try will use --isolated and ignores pip settings.

diff --git a/src/s2i/bin/assemble b/src/s2i/bin/assemble
--- a/src/s2i/bin/assemble
+++ b/src/s2i/bin/assemble
@@ -36,7 +36,15 @@ function install_tool() {
   {% endif %}
   VENV_DIR=$HOME/.local/venvs/$1
   virtualenv_bin "$VENV_DIR"
-  $VENV_DIR/bin/pip --isolated install -U $1$2  # Combines package name with [extras] if [extras] is defined as $2
+  # First, try to install the tool without --isolated which means that if you
+  # have your own PyPI mirror, it will take it from there. If this try fails, try it
+  # again with --isolated which ignores external pip settings (env vars, config file)
+  # and installs the tool from PyPI (needs internet connetion).
+  $VENV_DIR/bin/pip install -U $1$2  # Combines package name with [extras] if [extras] is defined as $2
+  if [ $? -ne 0 ]; then
+    echo "WARNING: Installation of $1 failed, trying again from official PyPI with pip --isolated"
+    $VENV_DIR/bin/pip --isolated install -U $1$2  # Combines package name with [extras] if [extras] is defined as $2
+  fi
   mkdir -p $HOME/.local/bin
   ln -s $VENV_DIR/bin/$1 $HOME/.local/bin/$1
 }
